{% set name = "conda-export" %}
{% set version = "0.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/olegtarasov/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 745f704a17691fc34e373fe803559d21b6170c0bcc04b8218598ab71903355dc

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - conda-export = conda_export:main

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
  run:
    - python >=3.6
    - pip
    - conda

test:
  commands:
    - conda-export -h

about:
  home: https://github.com/olegtarasov/conda-export
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Platform agnostic conda environment export'
  description: |
    An alternative to `conda env export` that helps create portable environment 
    specifications with minimal number of packages. Resulting specification is 
    similar to `conda env export --from-history`, but also includes packages 
    that were installed using `pip`.
  doc_url: https://github.com/olegtarasov/conda-export
  dev_url: https://github.com/olegtarasov/conda-export

extra:
  recipe-maintainers:
    - olegtarasov
